---

- name: Create web user
  action: user name=web comment="Web user" home=/var/www/

- name: Install Nginx Webserver
  action: apt package=nginx-extras state=present

- name: Create /etc/nginx/lib
  action: file path=/etc/nginx/lib state=directory

- name: Create /etc/nginx/ssl/default-server
  action: file path=/etc/nginx/ssl/default-server state=directory

- name: Install Nginx Config
  action: template src=nginx.conf dest=/etc/nginx/nginx.conf owner=root backup=yes
  notify: restart nginx

- name: Install Default Webserver Config
  action: template src=default.conf dest=/etc/nginx/sites-available/default owner=root backup=yes
  notify: restart nginx

- name: Install SSL key
  action: copy src=ssl/default.key dest=/etc/nginx/ssl/default-server/default.key owner=root mode=0400 backup=yes
  tags: ssl

- name: Install Certificate
  action: copy src=ssl/default.crt dest=/etc/nginx/ssl/default-server/default.crt owner=root mode=0400 backup=yes
  tags: ssl

- name: Install Muning Nginx config
  action: template src=munin.conf dest=/etc/nginx/lib/munin.conf owner=root backup=yes
  notify: restart nginx

- name: Install password file
  action: template src=htpasswd dest=/etc/nginx/htpasswd owner=root group=web mode=0440 backup=yes
  notify: restart nginx

#
# Not sure if I have to have this here, or if installing any file that 
# triggers a restart will implicity start nginx. Guess I'll find 
# out as I build more systems!
#
#- name: Start Nginx
#  action: service name=nginx state=started


