---

- name: Allow port 8000 for Splunk Search Head
  action: ufw to_port=8000 rule=allow
  when: is_splunk_indexer is defined

- name: Allow port 9997 for Splunk Indexer
  action: ufw to_port=9997 rule=allow
  when: is_splunk_indexer is defined

- name: Set up a symlink from /var/splunk/ to Splunk install
  action: file src=/opt/splunk dest=/var/splunk state=link force=yes

- name: Upload Splunk
  action: copy src=splunk.deb dest=/home/{{user}}/splunk.deb

- name: Install Splunk
  action: shell dpkg -i /home/{{user}}/splunk.deb creates=/opt/splunk

- name: Copying in script to start Splunk for the first time
  action: copy src=bin/install_splunk.sh dest=/home/{{user}} owner={{user}}


#
# Start of Splunk config files
#
- name: Install web.conf for Indexer
  action: copy src=indexer/web.conf dest=/opt/splunk/etc/system/local
  notify: restart splunk
  when: is_splunk_indexer is defined

- name: Install web.conf for Forwarder
  action: copy src=forwarder/web.conf dest=/opt/splunk/etc/system/local
  notify: restart splunk
  when: is_splunk_forwarder is defined

- name: Install Indexer inputs.conf (this will OFTEN change on indexers
    because of how Splunk stores its SSL passwords in the config file)
  action: template src=indexer/inputs.conf dest=/opt/splunk/etc/system/local
  notify: restart splunk
  when: is_splunk_indexer is defined

- name: Install Forwarder inputs.conf
  action: copy src=forwarder/inputs.conf dest=/opt/splunk/etc/system/local
  notify: restart splunk
  when: is_splunk_forwarder is defined

- name: Install Forwarder outputs.conf (this will OFTEN change on forwarders
    because of how Splunk stores its SSL passwords in the config file)
  action: template src=forwarder/outputs.conf dest=/opt/splunk/etc/system/local
  notify: restart splunk
  when: is_splunk_forwarder is defined

- name: Set up users/ directory
  action: file path=/opt/splunk/etc/users/admin/search/local/data/models state=directory

- name: Install btsync.json on Indexer
  action: copy src=indexer/btsync.json dest=/opt/splunk/etc/users/admin/search/local/data/models/btsync.json
  notify: restart splunk
  when: is_splunk_indexer is defined


