---
#
# Create a user
#

- name: "Creating user {{ username }}"
  action: user name={{ username }} shell=/bin/bash

- name: "Setting permissions on home directory for {{username}}"
  action: file path=~{{username}} mode=0700 state=directory

- name: "Creating {{username}}/.ssh directory"
  action: file path=~{{username}}/.ssh mode=0700 state=directory owner={{username}} group={{username}}
  tags: ssh

- name: "Installing ssh key {{ansible_ssh_public_key_file}}"
  action: copy src={{ansible_ssh_public_key_file}} dest="~{{username}}/.ssh/authorized_keys" 
    mode=0400 owner={{username}} group={{username}}
  tags: ssh

- name: Installing /etc/ssh/sshd_config
  action: template src=sshd_config dest=/etc/ssh/sshd_config owner=root group=root mode=644
  notify: restart sshd
  tags: ssh

- name: Installing /etc/sudoers
  action: template src=sudoers dest=/etc/sudoers owner=root group=root mode=0440


